site_name: "KENGI game engine: documentation"
site_url: https://kata.games/kengi-docs
repo_url: https://github.com/gaudiatech/kengi


theme:
  name: material
  font: false
  icon:
    logo: material/space-invaders


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gaudiatech/kengi
      name: kengi on Github


markdown_extensions:
  - admonition


plugins:
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
  
      languages:
        en:
          name: English
          build: true
        fr:
          name: Français
          build: true
          site_name: "Documentation pour KENGI: moteur de jeu"

      nav_translations:
        fr:
          Bidule: bidule.fr
          Topic1: Sujet1
          Topic2: Sujet2
